# Generated by Django 3.2.2 on 2021-07-07 00:44

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField(default=False)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolNumber', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField(default=False)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('parent_match', models.IntegerField(blank=True, null=True)),
                ('parent_game', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('teammate1', models.CharField(default='Teammate1', max_length=15)),
                ('teammate2', models.CharField(default='Teammate2', max_length=15)),
                ('teammate1_phone', phone_field.models.PhoneField(blank=True, default='56709', help_text='Contact phone number', max_length=31)),
                ('teammate2_phone', phone_field.models.PhoneField(blank=True, default='56709', help_text='Contact phone number', max_length=31)),
                ('seed', models.IntegerField(blank=True, default='0')),
                ('team_number', models.IntegerField(blank=True, null=True)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('point_differential', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-wins', '-point_differential'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament', max_length=50)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('pools_completed', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('matches', models.ManyToManyField(blank=True, to='tournament.TMatch')),
                ('pools', models.ManyToManyField(blank=True, to='tournament.Pool')),
                ('teams', models.ManyToManyField(blank=True, to='tournament.TTeam')),
            ],
        ),
        migrations.AddField(
            model_name='tmatch',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='tournament.tteam'),
        ),
        migrations.AddField(
            model_name='tmatch',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='tournament.tteam'),
        ),
        migrations.CreateModel(
            name='PRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('matches', models.ManyToManyField(blank=True, to='tournament.PMatch')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='tournament.PRound'),
        ),
        migrations.AddField(
            model_name='pool',
            name='teams',
            field=models.ManyToManyField(blank=True, to='tournament.TTeam'),
        ),
        migrations.AddField(
            model_name='pmatch',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PTeam1', to='tournament.tteam'),
        ),
        migrations.AddField(
            model_name='pmatch',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PTeam2', to='tournament.tteam'),
        ),
    ]
