# Generated by Django 3.2.2 on 2021-07-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
