# Generated by Django 3.2.2 on 2021-07-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_options',
            field=models.ManyToManyField(blank=True, to='tournament.PaymentOption'),
        ),
    ]
