# Generated by Django 3.2.2 on 2021-07-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210717_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entry_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
