# Generated by Django 3.2.2 on 2021-07-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20210717_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tteam',
            options={'ordering': ['losses', '-point_differential']},
        ),
        migrations.RemoveField(
            model_name='tteam',
            name='rank',
        ),
    ]
