# Generated by Django 3.2.2 on 2021-07-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20210717_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tteam',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
