# Generated by Django 3.2.2 on 2021-07-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tteam_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tteam',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
