# Generated by Django 3.2.2 on 2021-07-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
