# Generated by Django 3.2.2 on 2021-07-07 00:44

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_num', models.IntegerField(blank=True, null=True)),
                ('sub_bracket_num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('teammate1', models.CharField(max_length=15)),
                ('teammate2', models.CharField(max_length=15)),
                ('teammate1_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('teammate2_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('point_differential', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-wins', '-point_differential'],
            },
        ),
        migrations.CreateModel(
            name='TMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('winner', models.BooleanField(default=False)),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TTeam1', to='league.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TTeam2', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner1', models.BooleanField(default=False)),
                ('winner2', models.BooleanField(default=False)),
                ('winner3', models.BooleanField(default=False)),
                ('game1_team1_score', models.IntegerField(blank=True, null=True)),
                ('game1_team2_score', models.IntegerField(blank=True, null=True)),
                ('game2_team1_score', models.IntegerField(blank=True, null=True)),
                ('game2_team2_score', models.IntegerField(blank=True, null=True)),
                ('game3_team1_score', models.IntegerField(blank=True, null=True)),
                ('game3_team2_score', models.IntegerField(blank=True, null=True)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='league.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rounds_per_week', models.IntegerField(blank=True, null=True)),
                ('num_weeks', models.IntegerField(blank=True, null=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('brackets', models.ManyToManyField(blank=True, to='league.Bracket')),
                ('matches', models.ManyToManyField(blank=True, to='league.Match')),
                ('teams', models.ManyToManyField(blank=True, to='league.Team')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='matches',
            field=models.ManyToManyField(blank=True, to='league.TMatch'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='teams',
            field=models.ManyToManyField(blank=True, to='league.Team'),
        ),
    ]
