# Generated by Django 3.2.2 on 2021-07-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
