# Generated by Django 3.2.2 on 2021-07-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20210717_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['losses', '-point_differential']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='rank',
        ),
    ]
