# Generated by Django 3.2.2 on 2021-07-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photo_photogallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
    ]
