# Generated by Django 3.2.2 on 2021-07-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210713_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='instagramIndex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Index of instagram post (0 = most recent post)'),
        ),
    ]
