# Generated by Django 3.2.2 on 2021-07-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_media_instagramindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
