# Generated by Django 3.2.2 on 2021-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_media_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
