# Generated by Django 3.2.2 on 2021-07-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_media_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='instagramIndex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Index of instagram post (0 = most recent post) REQUIRED'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='media_id (will get autofilled)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Thumbnail (will get autofilled)'),
        ),
    ]
